# Generated by Django 3.0.3 on 2020-02-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messiah_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodstats',
            name='leftoverQ',
        ),
    ]
