# Generated by Django 3.0.3 on 2020-02-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messiah_api', '0002_remove_foodstats_leftoverq'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstats',
            name='leftoverQ',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
